name: run-tests
run-name: Run tests on latest push from ${{ github.actor }}
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python '3.9'
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip pytest nbmake opensees
          python -m pip install -e .
      - name: Unit tests
        run: python -m pytest
